packages:
  - server
  - client

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs
  - unrs-resolver

overrides:
  axios@<0.30.0: '>=0.30.0'
  axios@<0.30.2: '>=0.30.2'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  got@<11.8.5: '>=11.8.5'
  prismjs@<1.30.0: '>=1.30.0'
