packages:
  - server
  - client

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs
  - unrs-resolver

overrides:
  '@eslint/js': '>=10.0.0'
  '@stylistic/eslint-plugin': '>=5.0.0'
  axios@<0.30.2: '>=0.30.2'
  eslint: '>=10.0.0'
  got@<11.8.5: '>=11.8.5'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  minimatch@<10.2.1: '>=10.2.1'
  prismjs@<1.30.0: '>=1.30.0'
